name: Deploy to NAT VPS

on:
  push:
    branches:
      - main  # Jalankan setiap kali ada perubahan di branch 'main'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1.Checkout code dari repository
      - name: Checkout code
        uses: actions/checkout@v2

      # 2. Setup SSH untuk akses VPS NAT
      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
            ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      # 3. Deploy ke VPS menggunakan SSH
      - name: Deploy to VPS
        run: |
          ssh -o StrictHostKeyChecking=no 10433 root@38.46.219.162 "
            cd ~/project/mailer-services &&
            git pull origin main &&
            npm install &&
            pm2 restart mail-service || pm2 start index.js --name mail-service
            pm2 start "ngrok http 10202" --name mail-service-ngrok
          "
